### ISSUE TITLE
Fork for PDF / Djvu file uploads?

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/mediawiki-uploader#2]
Shrini, 

Can you fork this for PDF / Djvu file uploads?

**Comment by tshrinivasan** [comment]
For images, we give the metadata as title, description using gthumb.

Where will you give the metadata for PDF or djvu files?
Will it differ for each file?

**Comment by tshrinivasan** [comment]
Added PDF, DJVU upload scipt in this repo.

https://github.com/tshrinivasan/tools-for-wiki

Check the folder pdf-upload-commons
