### ISSUE TITLE
Add category to the uploaded files

### ISSUE THREAD

**Issue by tshrinivasan** [tshrinivasan/mediawiki-uploader#3]
Reported by : @tha-uzhavan 

Need facility to add category to the uploaded images.

**Comment by tshrinivasan** [comment]
Added this feature.

**Comment by tha-uzhavan** [comment]
Thanks brother. Is it possible to upload pdf file?

-_தகவலுழவன்_
Wikimedia-User-Name:\* Info-farmer  _Mobile:_+91 9095343342*
